baseURL = 'https://omerdolev.github.io/'
languageCode = 'en-us'
title = 'Mecha Blog'
theme = 'puppet'

[menu]
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = -100
[[menu.main]]
identifier = "archive"
name = "Archive"
url = "/archive/"
weight = 10
[[menu.main]]
identifier = "guide"
name = "Guide"
url = "/series/themes-guide/"
weight = 20
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 50
[[menu.main]]
identifier = "github"
name = "Github"
url = "https://github.com/roninro/hugo-theme-puppet/"
weight = 100

[params]
author = "Mecha Blog"
description = "Mecha Blog"
keywords = "blog,developer,personal"
img_404 = "img/404-bg.jpg"
img_home = "img/home-bg.png"